# Generated by Django 4.2.17 on 2025-01-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo_main/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Фото (главного страницы)',
                'verbose_name_plural': 'Фото (главного страницы)',
            },
        ),
    ]
