# Generated by Django 4.2.17 on 2024-12-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_over'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='awards/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'О нас (галерея)',
                'verbose_name_plural': 'О нас (галерея)',
            },
        ),
        migrations.AlterModelOptions(
            name='over',
            options={'verbose_name': 'Анимация', 'verbose_name_plural': 'Анимации'},
        ),
    ]
