# Generated by Django 4.2.17 on 2025-01-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsBottom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание награды')),
                ('awards', models.TextField(verbose_name='Награды')),
            ],
            options={
                'verbose_name': 'Награды',
                'verbose_name_plural': 'Награды',
            },
        ),
    ]
