# Generated by Django 4.2.17 on 2025-01-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_awardsbottom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название направление')),
                ('description', models.TextField(verbose_name='Описание вашего направление')),
            ],
        ),
    ]
