# Generated by Django 4.2.17 on 2025-01-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_direction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направление'},
        ),
    ]
