# Generated by Django 4.2.17 on 2025-01-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_direction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_graduated', models.TextField(verbose_name='Год окончание')),
                ('name', models.CharField(max_length=30, verbose_name='Имя ученика окончившийся')),
                ('direction', models.TextField(verbose_name='Направление студента')),
            ],
            options={
                'verbose_name': 'Окончившийся',
                'verbose_name_plural': 'Окончившийся',
            },
        ),
    ]
